micronaut:
  application:
    name: backend
  server:
    port: 8081

netty:
  default:
    allocator:
      max-order: 3

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://127.0.0.1:5432/school`}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:changeme}
    dialect: POSTGRES
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}