@startuml
'https://plantuml.com/class-diagram
' This is also a great resource https://plantuml-documentation.readthedocs.io/en/latest/formatting/all-skin-params.html

'Check this link for more configs https://plantuml.com/commons
scale 1.5

'Check this link for more themes https://plantuml.com/theme
!theme reddress-lightorange
' config
skinparam CaptionFontSize 11
skinparam linetype polyline
skinparam linetype ortho
skinparam groupInheritance 2
skinparam Shadowing true
caption School management diagram

/'
 Define classes
'/

class Course {
    UUID id
    String name
}

class Score {
    UUID id
    coursePK UUID
    studentPK UUID
    Integer weight
    date DateTime
}

abstract class Person {
    UUID id
    String firstName
    String lastName
    String gender
    DateTime dayOfBirth
    String Nationality
    String Email
    String Tel
}

class Student {

}

class Parent {
    String grade
    DateTime dayOfAdmission
    Boolean isStaff
}

class Classroom {
    UUID id
    String name
    String grade
    String level
}

class  ParentClass {
    id UUID
    parentPK UUID
    classPK UUID
    DateTime dateOfIntervention
}

class StudentClass {
    id UUID
    studentPK UUID
    classPK UUID
     enterDate
}

/'
Define notes
'/

note right of Class::grade
grade is the equivalent
of `serie` in english
end note

note right of Parent
This Method is tend to encapsulate
either a parent or an instructor
end note

note right of ParentClass::dateOfIntervention
dateOfIntervention is the date at which the instructor
begin instructing the class
end note

note left of Score::weight
It the correspondance of
<coeffcient> in mathetiques
end note

/'
Defines Relations
'/

' used to merge inheritance arrows header.
Person <|--  Student
Person <|--  Parent

Student "1..*" - "0..*" Parent

Student "1..*" - "1..*" Classroom
(Student, Classroom) .. StudentClass

Classroom "0..*" -left- "0..*" Parent
(Parent, Classroom) .. ParentClass

Course "0..*" -left- "0..*" Student
(Student, Course) .. Score
@enduml